import os
from datetime import datetime
from functools import wraps

import psycopg
from psycopg.rows import dict_row
from psycopg import errors
from flask import Flask, render_template, request, redirect, url_for, session, flash
from werkzeug.security import generate_password_hash, check_password_hash

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "dev-only-change-this-secret-key")
DATABASE_URL = os.environ.get("DATABASE_URL")


def connect():
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL is not configured. Add it in Vercel -> "
            "Project Settings -> Environment Variables."
        )
    return psycopg.connect(DATABASE_URL, row_factory=dict_row, connect_timeout=10)


def init_db():
    con = connect()
    try:
        with con.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT UNIQUE NOT NULL,
                    password TEXT NOT NULL,
                    fullname TEXT NOT NULL,
                    phone TEXT
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS items(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    item_type TEXT NOT NULL,
                    title TEXT NOT NULL,
                    category TEXT,
                    description TEXT,
                    location TEXT,
                    date_found_lost TEXT,
                    contact TEXT,
                    status TEXT DEFAULT 'เปิดประกาศ',
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(user_id) REFERENCES users(id)
                )
            """)
        con.commit()
    finally:
        con.close()


def ensure_db():
    init_db()


def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if "user_id" not in session:
            return redirect(url_for("login"))
        return view(*args, **kwargs)
    return wrapped


@app.route("/")
def index():
    if "user_id" in session:
        return redirect(url_for("home"))
    return redirect(url_for("login"))


@app.route("/login", methods=["GET", "POST"])
def login():
    ensure_db()
    if request.method == "POST":
        username = request.form["username"].strip()
        password = request.form["password"]
        con = connect()
        try:
            with con.cursor() as cur:
                cur.execute(
                    "SELECT id, username, password, fullname, phone FROM users WHERE username=%s",
                    (username,),
                )
                user = cur.fetchone()
        finally:
            con.close()
        if user and check_password_hash(user["password"], password):
            session["user_id"] = user["id"]
            session["fullname"] = user["fullname"]
            return redirect(url_for("home"))
        flash("ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง", "danger")
    return render_template("login.html")


@app.route("/register", methods=["GET", "POST"])
def register():
    ensure_db()
    if request.method == "POST":
        username = request.form["username"].strip()
        password = request.form["password"]
        fullname = request.form["fullname"].strip()
        phone = request.form["phone"].strip()

        if not username or not password or not fullname:
            flash("กรุณากรอกข้อมูลที่จำเป็น", "warning")
            return render_template("register.html")

        con = connect()
        try:
            with con.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO users(username, password, fullname, phone)
                    VALUES(%s, %s, %s, %s)
                    """,
                    (username, generate_password_hash(password), fullname, phone),
                )
            con.commit()
            flash("สมัครสมาชิกเรียบร้อยแล้ว", "success")
            return redirect(url_for("login"))
        except errors.UniqueViolation:
            con.rollback()
            flash("ชื่อผู้ใช้นี้มีอยู่แล้ว", "danger")
        finally:
            con.close()
    return render_template("register.html")


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


@app.route("/home")
@login_required
def home():
    ensure_db()
    con = connect()
    try:
        with con.cursor() as cur:
            cur.execute("SELECT COUNT(*) AS count FROM items WHERE item_type=%s", ("ของหาย",))
            lost = cur.fetchone()["count"]
            cur.execute("SELECT COUNT(*) AS count FROM items WHERE item_type=%s", ("ของที่พบ",))
            found = cur.fetchone()["count"]
    finally:
        con.close()
    return render_template("home.html", lost=lost, found=found)


@app.route("/items/new/<item_type>", methods=["GET", "POST"])
@login_required
def new_item(item_type):
    @app.route("/items/new/<item_type>", methods=["GET", "POST"])
@login_required
def new_item(item_type):
    if item_type == "lost":
        item_type_th = "ของหาย"
    elif item_type == "found":
        item_type_th = "ของที่พบ"
    else:
        return redirect(url_for("home"))

    if request.method == "POST":
        title = request.form["title"].strip()
        category = request.form["category"].strip()
        description = request.form["description"].strip()
        location = request.form["location"].strip()
        date_found_lost = request.form["date_found_lost"].strip()
        contact = request.form["contact"].strip()

        if not title:
            flash("กรุณาระบุชื่อสิ่งของ", "warning")
            return render_template(
                "item_form.html",
                item_type=item_type_th
            )

        con = connect()

        con.execute("""
            INSERT INTO items
            (user_id, item_type, title, category, description,
             location, date_found_lost, contact, created_at)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, (
            session["user_id"],
            item_type_th,
            title,
            category,
            description,
            location,
            date_found_lost,
            contact,
            datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ))

        con.commit()
        con.close()

        flash(f"บันทึกประกาศ{item_type_th}แล้ว", "success")
        return redirect(url_for("items"))

    return render_template(
        "item_form.html",
        item_type=item_type_th
    )

@app.route("/items")
@login_required
def items():
    ensure_db()
    keyword = request.args.get("q", "").strip()
    con = connect()
    try:
        with con.cursor() as cur:
            if keyword:
                k = f"%{keyword}%"
                cur.execute(
                    """
                    SELECT id, item_type, title, category, location, date_found_lost, status
                    FROM items
                    WHERE title ILIKE %s OR category ILIKE %s OR location ILIKE %s
                    ORDER BY id DESC
                    """,
                    (k, k, k),
                )
            else:
                cur.execute(
                    """
                    SELECT id, item_type, title, category, location, date_found_lost, status
                    FROM items ORDER BY id DESC
                    """
                )
            rows = cur.fetchall()
    finally:
        con.close()
    return render_template("items.html", items=rows, keyword=keyword)


@app.route("/items/<int:item_id>")
@login_required
def item_detail(item_id):
    ensure_db()
    con = connect()
    try:
        with con.cursor() as cur:
            cur.execute(
                """
                SELECT items.*, users.fullname
                FROM items
                JOIN users ON users.id = items.user_id
                WHERE items.id=%s
                """,
                (item_id,),
            )
            item = cur.fetchone()
    finally:
        con.close()

    if not item:
        flash("ไม่พบรายการนี้", "danger")
        return redirect(url_for("items"))
    return render_template("item_detail.html", item=item)


@app.route("/profile")
@login_required
def profile():
    ensure_db()
    con = connect()
    try:
        with con.cursor() as cur:
            cur.execute(
                "SELECT username, fullname, phone FROM users WHERE id=%s",
                (session["user_id"],),
            )
            user = cur.fetchone()
    finally:
        con.close()
    return render_template("profile.html", user=user)


if __name__ == "__main__":
    init_db()
    app.run(debug=True)
