import os
import sqlite3
from datetime import datetime
from functools import wraps

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # Optional for local SQLite-only development. Vercel installs it from requirements.txt.
    psycopg = None
    dict_row = None
from flask import Flask, flash, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "dev-only-change-this-secret-key")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SQLITE_DB = os.path.join(BASE_DIR, "lost_found.db")
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()


class DatabaseConnection:
    """Small compatibility wrapper so the app works with SQLite locally and Postgres on Vercel."""

    def __init__(self):
        self.is_postgres = bool(DATABASE_URL)
        if self.is_postgres:
            if psycopg is None:
                raise RuntimeError("psycopg is required when DATABASE_URL is set.")
            self.con = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        else:
            self.con = sqlite3.connect(SQLITE_DB)
            self.con.row_factory = sqlite3.Row

    def execute(self, query, params=()):
        if self.is_postgres:
            query = query.replace("?", "%s")
        return self.con.execute(query, params)

    def cursor(self):
        return self.con.cursor()

    def commit(self):
        self.con.commit()

    def rollback(self):
        self.con.rollback()

    def close(self):
        self.con.close()


def connect():
    return DatabaseConnection()


def init_db():
    con = connect()
    try:
        if con.is_postgres:
            con.execute("""
                CREATE TABLE IF NOT EXISTS users(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT UNIQUE NOT NULL,
                    password TEXT NOT NULL,
                    fullname TEXT NOT NULL,
                    phone TEXT
                )
            """)
            con.execute("""
                CREATE TABLE IF NOT EXISTS items(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    item_type TEXT NOT NULL,
                    title TEXT NOT NULL,
                    category TEXT,
                    description TEXT,
                    location TEXT,
                    date_found_lost TEXT,
                    contact TEXT,
                    status TEXT DEFAULT 'เปิดประกาศ',
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(user_id) REFERENCES users(id)
                )
            """)
        else:
            con.execute("""
                CREATE TABLE IF NOT EXISTS users(
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT UNIQUE NOT NULL,
                    password TEXT NOT NULL,
                    fullname TEXT NOT NULL,
                    phone TEXT
                )
            """)
            con.execute("""
                CREATE TABLE IF NOT EXISTS items(
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    item_type TEXT NOT NULL,
                    title TEXT NOT NULL,
                    category TEXT,
                    description TEXT,
                    location TEXT,
                    date_found_lost TEXT,
                    contact TEXT,
                    status TEXT DEFAULT 'เปิดประกาศ',
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(user_id) REFERENCES users(id)
                )
            """)
        con.commit()
    finally:
        con.close()


# Vercel imports app.py rather than running it as __main__, so initialize the
# persistent database when the function instance starts.
init_db()


def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if "user_id" not in session:
            return redirect(url_for("login"))
        return view(*args, **kwargs)

    return wrapped


@app.route("/")
def index():
    if "user_id" in session:
        return redirect(url_for("home"))
    return redirect(url_for("login"))


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"].strip()
        password = request.form["password"]

        con = connect()
        try:
            user = con.execute(
                "SELECT id, username, password, fullname, phone FROM users WHERE username=?",
                (username,),
            ).fetchone()
        finally:
            con.close()

        if user and check_password_hash(user["password"], password):
            session["user_id"] = user["id"]
            session["fullname"] = user["fullname"]
            return redirect(url_for("home"))

        flash("ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง", "danger")

    return render_template("login.html")


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form["username"].strip()
        password = request.form["password"]
        fullname = request.form["fullname"].strip()
        phone = request.form["phone"].strip()

        if not username or not password or not fullname:
            flash("กรุณากรอกข้อมูลที่จำเป็น", "warning")
            return render_template("register.html")

        con = connect()
        try:
            con.execute(
                "INSERT INTO users(username,password,fullname,phone) VALUES(?,?,?,?)",
                (username, generate_password_hash(password), fullname, phone),
            )
            con.commit()
            flash("สมัครสมาชิกเรียบร้อยแล้ว", "success")
            return redirect(url_for("login"))
        except Exception as exc:
            if isinstance(exc, sqlite3.IntegrityError) or (psycopg is not None and isinstance(exc, psycopg.errors.UniqueViolation)):
                con.rollback()
                flash("ชื่อผู้ใช้นี้มีอยู่แล้ว", "danger")
            else:
                con.rollback()
                raise
        finally:
            con.close()

    return render_template("register.html")


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


@app.route("/home")
@login_required
def home():
    con = connect()
    try:
        lost = con.execute(
            "SELECT COUNT(*) AS count FROM items WHERE item_type='ของหาย'"
        ).fetchone()["count"]
        found = con.execute(
            "SELECT COUNT(*) AS count FROM items WHERE item_type='ของที่พบ'"
        ).fetchone()["count"]
    finally:
        con.close()

    return render_template("home.html", lost=lost, found=found)


@app.route("/items/new/<item_type>", methods=["GET", "POST"])
@login_required
def new_item(item_type):
    if item_type not in ("ของหาย", "ของที่พบ"):
        return redirect(url_for("home"))

    if request.method == "POST":
        title = request.form["title"].strip()
        category = request.form["category"].strip()
        description = request.form["description"].strip()
        location = request.form["location"].strip()
        date_found_lost = request.form["date_found_lost"].strip()
        contact = request.form["contact"].strip()

        if not title:
            flash("กรุณาระบุชื่อสิ่งของ", "warning")
            return render_template("item_form.html", item_type=item_type)

        con = connect()
        try:
            con.execute("""
                INSERT INTO items
                (user_id,item_type,title,category,description,location,
                 date_found_lost,contact,created_at)
                VALUES(?,?,?,?,?,?,?,?,?)
            """, (
                session["user_id"], item_type, title, category, description,
                location, date_found_lost, contact,
                datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            ))
            con.commit()
        finally:
            con.close()

        flash(f"บันทึกประกาศ{item_type}แล้ว", "success")
        return redirect(url_for("items"))

    return render_template("item_form.html", item_type=item_type)


@app.route("/items")
@login_required
def items():
    keyword = request.args.get("q", "").strip()

    con = connect()
    try:
        if keyword:
            k = f"%{keyword}%"
            rows = con.execute("""
                SELECT id,item_type,title,category,location,date_found_lost,status
                FROM items
                WHERE title LIKE ? OR category LIKE ? OR location LIKE ?
                ORDER BY id DESC
            """, (k, k, k)).fetchall()
        else:
            rows = con.execute("""
                SELECT id,item_type,title,category,location,date_found_lost,status
                FROM items ORDER BY id DESC
            """).fetchall()
    finally:
        con.close()

    return render_template("items.html", items=rows, keyword=keyword)


@app.route("/items/<int:item_id>")
@login_required
def item_detail(item_id):
    con = connect()
    try:
        item = con.execute("""
            SELECT items.*, users.fullname
            FROM items
            JOIN users ON users.id = items.user_id
            WHERE items.id=?
        """, (item_id,)).fetchone()
    finally:
        con.close()

    if not item:
        flash("ไม่พบรายการนี้", "danger")
        return redirect(url_for("items"))

    return render_template("item_detail.html", item=item)


@app.route("/profile")
@login_required
def profile():
    con = connect()
    try:
        user = con.execute(
            "SELECT username, fullname, phone FROM users WHERE id=?",
            (session["user_id"],),
        ).fetchone()
    finally:
        con.close()
    return render_template("profile.html", user=user)


if __name__ == "__main__":
    app.run(debug=True)
