"""Copy the existing lost_found.db data into the Postgres database in DATABASE_URL.

Usage:
    set DATABASE_URL=postgresql://...
    python migrate_sqlite_to_postgres.py

The script preserves user/item IDs so existing relationships remain intact.
"""

import os
import sqlite3

import psycopg
from psycopg.rows import dict_row

SQLITE_DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "lost_found.db")
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if not DATABASE_URL:
    raise SystemExit("DATABASE_URL is not set.")

sqlite_con = sqlite3.connect(SQLITE_DB)
sqlite_con.row_factory = sqlite3.Row
pg_con = psycopg.connect(DATABASE_URL, row_factory=dict_row)

try:
    pg_con.execute("""
        CREATE TABLE IF NOT EXISTS users(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            fullname TEXT NOT NULL,
            phone TEXT
        )
    """)
    pg_con.execute("""
        CREATE TABLE IF NOT EXISTS items(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            item_type TEXT NOT NULL,
            title TEXT NOT NULL,
            category TEXT,
            description TEXT,
            location TEXT,
            date_found_lost TEXT,
            contact TEXT,
            status TEXT DEFAULT 'เปิดประกาศ',
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
    """)

    users = sqlite_con.execute("SELECT * FROM users ORDER BY id").fetchall()
    items = sqlite_con.execute("SELECT * FROM items ORDER BY id").fetchall()

    for row in users:
        pg_con.execute("""
            INSERT INTO users(id, username, password, fullname, phone)
            VALUES(%s, %s, %s, %s, %s)
            ON CONFLICT (id) DO UPDATE SET
                username=EXCLUDED.username,
                password=EXCLUDED.password,
                fullname=EXCLUDED.fullname,
                phone=EXCLUDED.phone
        """, tuple(row))

    for row in items:
        pg_con.execute("""
            INSERT INTO items(
                id,user_id,item_type,title,category,description,location,
                date_found_lost,contact,status,created_at
            )
            VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (id) DO UPDATE SET
                user_id=EXCLUDED.user_id,
                item_type=EXCLUDED.item_type,
                title=EXCLUDED.title,
                category=EXCLUDED.category,
                description=EXCLUDED.description,
                location=EXCLUDED.location,
                date_found_lost=EXCLUDED.date_found_lost,
                contact=EXCLUDED.contact,
                status=EXCLUDED.status,
                created_at=EXCLUDED.created_at
        """, tuple(row))

    # Keep identity sequences ahead of imported IDs.
    if users:
        pg_con.execute("SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1), true) FROM users")
    if items:
        pg_con.execute("SELECT setval(pg_get_serial_sequence('items', 'id'), COALESCE(MAX(id), 1), true) FROM items")

    pg_con.commit()
    print(f"Migrated {len(users)} users and {len(items)} items.")
finally:
    sqlite_con.close()
    pg_con.close()
